version: '2.0'

services:
  moneywise-ui:
      image: moneywise-ui
      build:
        context: ./ui
        # TODO: pass env var for base urls
      depends_on:
        - moneywise-backend
      ports:
       - 8080:80

  moneywise-backend:
    image: moneywise-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - 8000:8000

  myadmin:
    image: phpmyadmin/phpmyadmin
    hostname: myadmin
    networks:
      - moneywise
    ports:
      - 8090:80
    environment:
      PMA_HOST: mysql
