version: '3.4'

services:
  moneywise-backend:
    env_file:
      - backend-variables.env # This file is NOT committed to the REPO. This should only exist on the corresponding environments defined by the users.


