version: '3.4'

networks:
  moneywise:
    name: moneywise

services:
  moneywise-ui:
    image: moneywise-ui
    build:
      context: ./ui
      args:
        - REACT_APP_MONEYWISE_BASE_URL=${API_BASE_URL}
    depends_on:
      - moneywise-backend
    ports:
      - 8080:80

  moneywise-backend:
    image: moneywise-backend
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    networks:
      - moneywise
    ports:
      - 8000:8000
    environment:
      - CORS_ORIGIN_WHITELIST_CSV=${UI_ORIGIN}
