service: make-transactions
app: transactions
org: jamesfulford

plugins:
  - serverless-python-requirements

provider:
  name: aws
  runtime: python3.8
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  environment:
    AUTH0_CLIENT_ID: ${param:AUTH0_CLIENT_ID}
    AUTH0_CLIENT_PUBLIC_KEY: ${param:AUTH0_CLIENT_PUBLIC_KEY}

functions:
  auth:
    handler: auth.auth
    cors: true
  get_instances_from_rules:
    handler: handler.get_instances_from_rules
    events:
      - http:
          path: project-transactions
          method: post
          cors: true
          authorizer: auth

resources:
  Resources:
    # This response is needed for custom authorizer failures cors support ¯\_(ツ)_/¯
    GatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: EXPIRED_TOKEN
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
    AuthFailureGatewayResponse:
      Type: 'AWS::ApiGateway::GatewayResponse'
      Properties:
        ResponseParameters:
          gatewayresponse.header.Access-Control-Allow-Origin: "'*'"
          gatewayresponse.header.Access-Control-Allow-Headers: "'*'"
        ResponseType: UNAUTHORIZED
        RestApiId:
          Ref: 'ApiGatewayRestApi'
        StatusCode: '401'
