# Generated by Django 3.1.3 on 2020-11-07 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rule',
            new_name='RuleX',
        ),
    ]
