# Generated by Django 3.1.1 on 2020-11-11 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='rule',
            name='frequency',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='rule',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
