# Generated by Django 3.1.1 on 2020-11-11 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20201111_2021'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='frequency',
            new_name='rrule',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='amount',
            new_name='value',
        ),
    ]
