# Generated by Django 3.1.3 on 2020-11-07 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20201107_1430'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RuleX',
            new_name='Rule',
        ),
    ]
